set nocompatible
filetype off
" syntax and colors
syntax on
" line numbers
set number
" 2 spaces indent
set expandtab
set shiftwidth=2
set softtabstop=2
" prevent not-working delete key
set backspace=indent,eol,start
" paste from other applications without messing the indent
set paste
