" Inicio de la configuracion de Bundle
set nocompatible              " be iMproved, required
filetype off                  " required

" Colores y sintaxis
syntax on

" Numeros de linea
set number

" Indentado
set smartindent
set tabstop=2
set shiftwidth=2
set expandtab

" Prevenir que la tecla Delete no funcione correctamente
set backspace=indent,eol,start

" Corregir el autoindent al pegar
set paste
