# The following lines were added by compinstall

zstyle ':completion:*' completer _expand _complete _ignored _correct _approximate
zstyle ':completion:*' matcher-list 'm:{[:lower:][:upper:]}={[:upper:][:lower:]}' 'l:|=* r:|=*'
zstyle :compinstall filename '/Users/pol/.zshrc'

autoload -Uz compinit
compinit
# End of lines added by compinstall
# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000
bindkey -e
# End of lines configured by zsh-newuser-install

# VARS
export PATH="$PATH:/opt/bin"
setopt interactivecomments # allow interactive comments
which subl > /dev/null
if [ $? -eq 0 ]; then
	export EDITOR="subl -w"
else
	export EDITOR="vim"
fi

# ALIASES
alias g='git'
alias gt='git status'
alias gl='git pull'
alias gp='git push'
alias glog='git log --oneline --decorate --color --graph'

# PROMPT
setopt PROMPT_SUBST
autoload -Uz colors && colors
PROMPT='%{$fg[cyan]%}(%m) $(gst)> '

# Bind Keys to History 
autoload -U history-search-end
zle -N history-beginning-search-backward-end history-search-end
zle -N history-beginning-search-forward-end history-search-end
bindkey "^[[A" history-beginning-search-backward-end
bindkey "^[[B" history-beginning-search-forward-end
